import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { Box, Button, Center, Container, Heading } from "@chakra-ui/react";

import Header from "../components/Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Container maxW="container.lg">
        <Box pt={24} pb={24}>
          <Center flexDirection="column">
            <Heading mb={8}>Make sense of your on-chain data</Heading>
            <Link href="/snapshots/new">
              <Button>Create a Snapshot</Button>
            </Link>
          </Center>
        </Box>
      </Container>
    </>
  );
};

export default Home;
