import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";

import {
  Box,
  Button,
  Checkbox,
  Code,
  Container,
  Flex,
  FormControl,
  FormHelperText,
  FormLabel,
  Heading,
  Input,
  Radio,
  RadioGroup,
  Select,
  Stack,
  Textarea,
} from "@chakra-ui/react";
import { useForm } from "react-hook-form";
import { useAccount } from "wagmi";

import Header from "../../components/Header";

const Home: NextPage = () => {
  const chains = [
    "ETH Mainnet",
    "Polygon",
    "Arbitrum",
    "Avalanche",
    "Fantom",
    "BSC",
  ];

  const providers = {
    "Eth Mainnet":
      "https://eth-mainnet.alchemyapi.io/v2/NGtUbewnL3eCvtxqJQr_biDfjQjPOCBD",
  };

  const {
    register,
    handleSubmit,
    watch,
    setValue,
    formState: { errors },
  } = useForm();

  const [{ data: accountData }, disconnect] = useAccount({
    fetchEns: true,
  });

  const router = useRouter();

  const onSubmit = async (data: any) => {
    console.log(data);

    data.creator = accountData?.address;
    const { contract_abi, event } = data;
    data.contract_abi = JSON.parse(contract_abi);
    data.event = JSON.parse(event);

    const response = await fetch("http://localhost:8000/api/snapshots/", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data), // body data type must match "Content-Type" header
    });
    const result = await response.json();
    console.log(result);

    const { id } = result;

    router.push(`/snapshots/${id}`);
  };

  const contractAbi = watch("contract_abi");
  const event = watch("event");

  const events = JSON.parse(contractAbi || "[]").filter(
    (item: { type: string }) => item.type === "event"
  );
  const supportsTokenBalance =
    JSON.parse(contractAbi || "[]").filter(
      (item: { type: string; name: string }) =>
        item.type === "function" && item.name === "balanceOf"
    ).length > 0;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container maxW="container.lg">
        <Heading pt={24} pb={12}>
          Create a snapshot
        </Heading>

        <FormControl mb={8}>
          <FormLabel htmlFor="chain">Chain</FormLabel>
          <RadioGroup id="chain" defaultValue={"ETH Mainnet"}>
            <Stack direction="row">
              {chains.map((value) => (
                <Radio key={value} value={value} {...register("chain")}>
                  {value}
                </Radio>
              ))}
            </Stack>
          </RadioGroup>
          <FormHelperText>
            HolderSnap will query data from this chain to create your snapshot
          </FormHelperText>
        </FormControl>
        <FormControl mb={8}>
          <FormLabel htmlFor="contract_address">Contract Address</FormLabel>
          <Input
            id="contract_address"
            {...register("contract_address")}
            placeholder="0x..."
          />
        </FormControl>
        <FormControl mb={8}>
          <FormLabel htmlFor="contract_abi">Contract ABI</FormLabel>
          <Textarea
            id="contract_abi"
            placeholder="[...]"
            {...register("contract_abi")}
          />
        </FormControl>
        {events.length > 0 && (
          <FormControl mb={8}>
            <FormLabel htmlFor="event">Event</FormLabel>
            <Select
              id="event"
              placeholder="Select event"
              {...register("event")}
            >
              {events.map((event: { name: string }) => (
                <option key={event.name} value={JSON.stringify(event)}>
                  {event.name}
                </option>
              ))}
            </Select>
            <FormHelperText>
              Specify the event you would like to query
            </FormHelperText>
          </FormControl>
        )}
        {event && (
          <>
            <Heading fontSize="xl" mb={4} mt={4}>
              Filter Events
            </Heading>
            {JSON.parse(event).inputs.map(
              (input: { name: string; type: string }) => (
                <FormControl key={input.name} mb={8}>
                  <FormLabel>
                    {input.name} (<Code>{input.type}</Code>)
                  </FormLabel>
                  <Flex flexDirection="row">
                    <Input {...register(`argument_filters.${input.name}`)} />
                    {input.type === "address" && (
                      <Checkbox
                        {...register(`captured_values.${input.name}`)}
                        ml={4}
                      >
                        Capture
                      </Checkbox>
                    )}
                  </Flex>
                </FormControl>
              )
            )}
            {supportsTokenBalance && (
              <FormControl mb={8}>
                <FormLabel>Minimum Token Balance</FormLabel>
                <Flex flexDirection="row">
                  <Input
                    {...register("token_balance", { valueAsNumber: true })}
                  />
                </Flex>
              </FormControl>
            )}
            <FormControl mb={8}>
              <FormLabel>From Block Number</FormLabel>
              <Flex flexDirection="row">
                <Input {...register("from_block", { valueAsNumber: true })} />
              </Flex>
            </FormControl>
            <FormControl mb={8}>
              <FormLabel>To Block Number</FormLabel>
              <Flex flexDirection="row">
                <Input {...register("to_block", { valueAsNumber: true })} />
              </Flex>
            </FormControl>
          </>
        )}
        <Box mb={24}>
          <Button
            isDisabled={!contractAbi || !event}
            onClick={handleSubmit(onSubmit)}
          >
            Generate Snapshot
          </Button>
        </Box>
      </Container>
    </>
  );
};

export default Home;
