# Generated by Django 4.0.2 on 2022-02-19 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=42, null=True)),
                ('deployed_block_number', models.IntegerField(default=3914495)),
                ('abi', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.TextField()),
                ('contract_address', models.CharField(max_length=42)),
                ('contract_abi', models.JSONField()),
                ('event', models.JSONField()),
                ('from_block', models.IntegerField(default=3914495)),
                ('to_block', models.IntegerField(default=99999999)),
                ('argument_filters', models.JSONField()),
                ('captured_values', models.JSONField()),
                ('events_cid', models.TextField()),
                ('events_count', models.BigIntegerField(default=0)),
                ('addresses_cid', models.TextField()),
                ('addresses_count', models.BigIntegerField(default=0)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['updated_at', 'to_block', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('snapshots', models.ManyToManyField(blank=True, to='core.Snapshot')),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snapshot')),
            ],
        ),
    ]
