# Generated by Django 4.0.2 on 2022-02-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.TextField()),
                ('contract_address', models.TextField()),
                ('contract_abi', models.JSONField()),
                ('event', models.JSONField()),
                ('from_block', models.IntegerField(default=0)),
                ('to_block', models.IntegerField(default=99999999)),
                ('argument_filters', models.JSONField()),
                ('captured_values', models.JSONField()),
                ('events_cid', models.TextField()),
                ('events_count', models.BigIntegerField(default=0)),
                ('addresses_cid', models.TextField()),
                ('addresses_count', models.BigIntegerField(default=0)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42)),
            ],
        ),
    ]
