# Generated by Django 4.0.2 on 2022-02-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='token_balance',
            field=models.IntegerField(default=0),
        ),
    ]
