# Generated by Django 4.0.2 on 2022-02-20 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_snapshots'),
        ('core', '0002_snapshot_token_balance'),
    ]

    operations = [
    ]
