# Generated by Django 4.0.2 on 2022-02-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20220220_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='rpc_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
