# Generated by Django 4.0.2 on 2022-02-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_snapshot_rpc_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='creator',
            field=models.CharField(default='0x0000000000000000000000000000000000000000', max_length=42),
        ),
    ]
